name: Maven CI

on:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Configure maven for two different repositories
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: |
            [
              {
                "id": "github-read",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              },
              {
                "id": "github",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]

      - name: Debug library visibility and architecture
        run: |
          uname -m
          ls -la ${{ github.workspace }}/lib

      - name: Build with Maven and run unit tests
        run: mvn --batch-mode verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LD_LIBRARY_PATH: ${{ github.workspace }}/lib

  deploy-to-packages:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Crucial for publishing to GitHub Packages

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Configure maven for two different repositories
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: |
            [
              {
                "id": "github-read",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              },
              {
                "id": "github",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]

      - name: Deploy package with Maven
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LD_LIBRARY_PATH: ${{ github.workspace }}/lib

